// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadDirectories(arg1:string):Promise<main.LoadDirs>;

export function LoadDirectory(arg1:string):Promise<Array<main.FileDetails>>;

export function LoadFileContents(arg1:string):Promise<string>;
