// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadDirectories(arg1) {
  return window['go']['main']['App']['LoadDirectories'](arg1);
}

export function LoadDirectory(arg1) {
  return window['go']['main']['App']['LoadDirectory'](arg1);
}

export function LoadFileContents(arg1) {
  return window['go']['main']['App']['LoadFileContents'](arg1);
}
